@url=http://localhost:3000/user
# @url=https://lahman-backend.onrender.com
@userid=656c1cd8892354c226458da4
//check database connection
POST {{url}}/signup
Content-Type: application/json

{ 
  "name":"vaibhav1",
  "username":"vaibhav_kumar11",
  "email":"vaibhatezan1@email.com",
  "password":"vaibhav",
  "image":"thi is image "
}   

###

POST {{url}}/login
Content-Type: application/json

{   "username":"vaibhav kumar",
    "email":"vaibhatezan@gmail.omc",
    "password":"vaibhav"
}


###


PATCH {{url}}/user/{{userid}}/updateuser
Content-Type: application/json

{
    "email":"vaibhatezan@gmail.omc"
}
