@url=http://localhost:3000/user
@url=https://user-nuox.onrender.com/user
@userid=656c1cd8892354c226458da4
//check database connection
POST {{url}}/signup
Content-Type: application/json

{ 
  "name":"vaibhav2",
  "username":"vaibhav_kumar112",
  "email":"vaibhatezan12@email.com",
  "password":"vaibhav",
  "image":"thi is image "
}   

###

POST {{url}}/login
Content-Type: application/json

{   "username":"vaibhav kumar",
    "email":"vaibhatezan@gmail.omc",
    "password":"vaibhav"
}


###


PATCH {{url}}/{{userid}}/updateuser
Content-Type: application/json

{
    "email":"vaibhatezan@gmail.omc"
}
